# Generated by Django 4.2 on 2023-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_description_task_isdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
